### PR TITLE
Feature/scala3

### PR DESCRIPTION
**Pull request by vitaliihonta**

### CODE REVIEW

**Comment by oridag** [comment]
Hi, I'm interested in giving zio-temporal a try but I'm on Scala 3. Is this PR going to be merged and released soon?

**Comment by vitaliihonta** [comment]
@oridag Hi, I appreciate your interest in temporal! 
Sure, I'm still working on Scala 3 support, I just paused to proceed with other projects.
If you want to give it a try, I'll switch back to this PR and complete it soon 😄

**Comment by vitaliihonta** [comment]
@oridag JFYI, I did the hardest work for Scala 3 implementation. Tests and examples are now working for Scala 3 🎉 . 
There are still a few things that I need to implement and optimize, but I hope by the end of this week, it will be ready 😄  
After that, I gonna start adding a website with documentation.

**Comment by oridag** [comment]
That's fantastic, thank you! 
I'm going on a vacation for a couple of weeks and then there's something else that will require my attention for a while so no rush from my end. I hope I can get back to Temporal and give zio-temporal a try sometime in September.

**Comment by vitaliihonta** [comment]
Just a few enhancements left, I'll add them later in a separate PR.
Everything else seems to be working (finaaaaaalyyy)

**Comment by oridag** [comment]
Hey @vitaliihonta, just got around to implement the Temporal integration and am stating to look into zio-temporal so I'll probably have some questions...
One thing I'm worried about is that it looks like the workflow execution code will block waiting for the results of activities. I can see that activity execution can be made non-blocking but not the workflow execution. Am I right? Is this a limitation in Temporal?

Anyway, thanks for open sourcing this, it looks very nice!
I might have more questions down the line, is there a more appropriate to ask them? Perhaps start a zio-temporal channel on the zio server in Discord?

**Comment by vitaliihonta** [comment]
Hey @oridag! Sure, feel free to reach me out in Zio discord 🙂

Regarding blocking for activities result. I'll suggest to read the temporal documentation. The workflow implementation for JVM is kinda tricky. It relies on thread interruptions and interface proxies, so the workflow code is not executed  exactly in the way it's declared

**Pull request merged**
