### PR TITLE
Remove reflections

### PR DESCRIPTION
**Pull request by hoangmaihuy**
# Changes being made
Remove `reflections` from dependencies. I've made changes in two places:
- `ClassTagUtils`: Simply replace `reflections` usage with Java's reflection methods
- `ScalapbPayloadConverter`: `reflections` is being used for scanning Scalapb's companion objects, but instead we can get companion object from `valueClass`.

# Additional context
[reflections](https://github.com/ronmamo/reflections) is not under active development and maintenance, and it has serveral issues on newer JDKs, please see https://github.com/ronmamo/reflections/issues/440 and https://github.com/ronmamo/reflections/issues/377 for example.

### CODE REVIEW

**Comment by vitaliihonta** [comment]
Hi @hoangmaihuy! Thank you so much for your contribution! That's a very clever change. I didn't expect it's that straightforward to drop reflections 😄 
Before merging, I will check if everything works fine in my example projects. I hope to do it soon

**Comment by vitaliihonta** [comment]
I found some issues while decoding ADTs. I will figure it out on my own 😃

**Comment by hoangmaihuy** [comment]
@vitaliihonta Thank you a lot for this great work, glad I can help! 😄

**Comment by vitaliihonta** [comment]
TODOs
- [ ] Check if the default ScalaPB generated oneOf's work work
- [ ] Develop a workaround for classes generated using `sealedValue`

**Comment by hoangmaihuy** [comment]
@vitaliihonta Workaround for `sealedValue` might be like this, I've tested on my local and it worked!
Please let me know if it works on your example projects

```scala
  private def getClassCompanion[T](
    valueClass: Class[T]
  ): GeneratedMessageCompanion[GeneratedMessage] = {
    val companionClass = Class.forName(valueClass.getName + "$")
    companionClass
      .getDeclaredField(scalaModuleField)
      .get(null)
      .asInstanceOf[GeneratedMessageCompanion[GeneratedMessage]]
  }

  private def getCompanion[T](
    typeUrl: String,
    valueClass: Class[T]
  ): GeneratedMessageCompanion[GeneratedMessage] = {
    println(s"typeUrl = $typeUrl")
    println(s"valueClass = ${valueClass.getName}")
    if (valueClass.isInterface && valueClass.getInterfaces.contains(classOf[GeneratedSealedOneof])) {
      val subClassType = typeUrl.split("\\.").last
      val subClassName = valueClass.getName.replace(valueClass.getSimpleName, subClassType)
      println(s"subClassName = ${subClassName}")
      getClassCompanion(Class.forName(subClassName))
    } else {
      getClassCompanion(valueClass)
    }
  }
```

**Comment by vitaliihonta** [comment]
Hey @hoangmaihuy, could you merge my updates from #120 into your branch? I cannot push my changes to your fork directly, but I want to keep you in the commit history 😃

**Comment by hoangmaihuy** [comment]
@vitaliihonta I've merged #120 into this branch 😄

**Comment by vitaliihonta** [comment]
@hoangmaihuy, thank you so much for your contribution 🙌 
I'm going to release it in 0.5.0 as `makeAutoload` method was removed

**Pull request merged**
